### ISSUE TITLE
Maybe add bootlint

### ISSUE THREAD

**Issue by Tiliavir** [EvgenyOrekhov/lints#5]
https://github.com/twbs/bootlint

**Comment by EvgenyOrekhov** [comment]
Implemented in 7.0.0

If you already have a `.lints.json`, in order to use Bootlint you
need to add it to your `.lints.json`, as in [src/default.lints.json](src/default.lints.json).

If you wish to disable some of the Bootlint's linters you can
create a `.bootlintrc.json` file in the root of your project with
an array of string linter IDs to disable, e. g.

```json
["W001", "W002", "W003"]
```

**Comment by EvgenyOrekhov** [comment]
Added line and column numbers to Bootlint's warnings in 8.0.0.

Undefined location will be represented as `line 0 column 0`.
